#index:
#    path: /
#    controller: App\Controller\DefaultController::index

not_found:
    path: /404.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  '404.html.twig'
